version: "1"
services:
- type: web
  name: AzizAssistant_Render-1
  runtime: python
  repo: https://github.com/Mirfayziev/AzizAssistant_Render
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python bot.py
  autoDeployTrigger: commit
