services:
  - type: worker
    name: my-telegram-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install python-telegram-bot==20.7
      pip install openai==1.3.0
      pip install deep-translator==1.11.4
      pip install SpeechRecognition==3.10.0
      pip install pydub==0.25.1
      pip install requests==2.31.0
      pip install python-dotenv==1.0.0
    startCommand: python bot.py
